### ISSUE TITLE
Change node edge color

### ISSUE THREAD

**Issue by ShafahJiitak** [wbkd/react-flow#1470]
How to change the color of this? Anyone please

![Screenshot 2021-08-26 at 10 31 35 PM](https://user-images.githubusercontent.com/78135779/131005181-cf6c1303-b09a-48eb-9c96-c89421ea9ec5.jpg)

**Comment by moklick** [comment]
for an input node for example:

```css 
.react-flow__node-input .react-flow__handle {
    background: #0041d0;
}
```

for every node:

```css 
.react-flow__node .react-flow__handle {
    background: teal;
}
```
