### ISSUE TITLE
Cannot customise not edge pointer

### ISSUE THREAD

**Issue by Shafahummer** [wbkd/react-flow#1471]
![Screenshot 2021-08-27 at 5 04 00 PM](https://user-images.githubusercontent.com/44742741/131121609-f4c3d77f-9c17-40d7-a974-c56747d0f26e.jpg)

How to customise the node edge like this? I cannot do it. Anyone please

**Comment by oferitz** [comment]
You can either customize it globally with CSS
```css
  .react-flow {
    .react-flow__handle {
      width: 12px;
      height: 12px;
      border: 2px solid dodgerblue;
      background-color: powderblue;
      
    }
  }
  ```
  
  Or you can create your own custom node with custom handles:
  https://reactflow.dev/examples/custom-node/
