### ISSUE TITLE
null node.__rf.width and node.__rf.height

### ISSUE THREAD

**Issue by AlyonaGN** [wbkd/react-flow#1639]
Hi!

I am trying to implement the logic that is described here - https://github.com/wbkd/react-flow/issues/5, but have some troubles with  node.__rf.height and node.__rf.width as they are null. 
This is the function in which I refer to these variables:

```
const dagreGraph = new dagre.graphlib.Graph();
dagreGraph.setDefaultEdgeLabel(() => ({}));

export const GetLayoutedElements = (elements, direction = "LR") => {
    console.log("elll", elements);
    const isHorizontal = direction === "LR";
    dagreGraph.setGraph({ rankdir: direction });

    elements.forEach((el) => {
        if (isNode(el)) {
            dagreGraph.setNode(el.id, {
                width: el.__rf.width,
                height: el.__rf.height,
            });
        } else {
            dagreGraph.setEdge(el.source, el.target);
        }
    });

    dagre.layout(dagreGraph);

    return elements.map((el) => {
        if (isNode(el)) {
            const nodeWithPosition = dagreGraph.node(el.id);
            el.targetPosition = isHorizontal ? "left" : "top";
            el.sourcePosition = isHorizontal ? "right" : "bottom";

           
            el.position = {
                x: nodeWithPosition.x - nodeWidth / 2 + Math.random() / 1000,
                y: nodeWithPosition.y - nodeHeight / 2,
            };
        }

        return el;
    });
};
```
My elements are of this type:

```
{
    data: {label: 'epilogue'}
    id: "434ccf23-c948-3f6d-73f3-ac21057603ff"
    position: {x: 0, y: 0}
    sourcePosition: "left"
    targetPosition: "right"
    type: "topic"
}
```
And when they are extracted from the store they look like this:
```
{
    data: {label: 'Start'}
    id: "a94a766f-111d-fc31-ea97-9eb1f4c2e673"
    position: {x: -99.99983210854778, y: -50}
    sourcePosition: "right"
    targetPosition: "left"
    type: "startOfTree"
    __rf:
    handleBounds: {}
    height: null
    isDragging: false
    position: {x: -99.99983210854778, y: -50}
    width: null
    [[Prototype]]: Object
    [[Prototype]]: Object
}
```

Could you please let me know why this may happening?
