### ISSUE TITLE
Styling marquee selection

### ISSUE THREAD

**Issue by flexplatox** [wbkd/react-flow#1640]
Is there an easy way to style the marquee selection element? The default is light blue with a dashed border.

**Comment by moklick** [comment]
You could overwrite the CSS rules.

This is the default style 

```css
.react-flow__nodesselection-rect {
  background: rgba(0, 89, 220, 0.08);
  border: 1px dotted rgba(0, 89, 220, 0.8);
}
```
