### ISSUE TITLE
Controls horizontal

### ISSUE THREAD

**Issue by kaoding** [wbkd/react-flow#3084]
### Please describe the feature that you want to propose

![image](https://github.com/wbkd/react-flow/assets/18542211/19c48de1-1d32-4485-900e-f4c7378405f3)

**Comment by moklick** [comment]
you can achieve this with CSS:

```CSS
.react-flow__controls {
  display: flex;
}
```
