### ISSUE TITLE
Styling the default CSS properties needs `!important`

### ISSUE THREAD

**Issue by ChristoRibeiro** [wbkd/react-flow#491]
I'm currently using Nextjs with the library and it's a pleasure to use it! Thanks for the work @moklick!

I'm struggling when I try to override the default CSS properties provided by the lib. I need to add `!important` everywhere to make it work. I guess the example `background: red` from the README works because the property is not used from the lib. Here some examples from my CSS file:

```css
/* my.css */

/* work 
 * because the property background is not used by react-flow from the className .react-flow */
.react-flow {
  background: red;
}

/* don't work 
 * because react-flow style is injected into the <head> after my css and use the property background-color and so has the priority over my style */
.react-flow__node-default {
  background-color: #FFF; 
}

/* it work */
.react-flow__node-default {
  background-color: #FFF !important; 
}

/* don't work
 * if I use the !important above I can't change the color of handle
 * because my .react-flow__node-default above has the priority */
.react-flow__node-default:hover .react-flow__handle {
  border-color: #AAA !important;
}
```

Any ideas to make the styling experience better?

**Comment by moklick** [comment]
Hey! I am also not very happy with the solution right now. We will definitely change the styling behaviour sometime. 
For now you can try to use a stronger selector like:

```css 
.react-flow .react-flow__node-default {
  background-color: #FFF; 
}
```

I hope it helps.
